language: python
python:
  - "3.7"
install:
  - python setup.py install
script: nosetests -a '!obsolete'
env:
  - RUNENV=travis MAL_USERNAME=py3mal1 MAL_PASSWORD=KomplikaltJelszo TESTS_SQUID_ADDRESS=mal-squid.k8s.pushrbx.net:3128
